version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_waipro
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Benessere84++
      - N8N_HOST=n8n.waipro.it
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.waipro.it/
      - GENERIC_TIMEZONE=Europe/Rome
      - N8N_METRICS=true

      # Database (SQLite internal - or configure Postgres below)
      - DB_TYPE=sqlite

      # Email configuration (optional)
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=your-email@gmail.com
      - N8N_SMTP_PASS=your-app-password
      - N8N_SMTP_SENDER=your-email@gmail.com

      # Encryption key (generate with: openssl rand -base64 32)
      - N8N_ENCRYPTION_KEY=R/sCE9RdnKd1qGlYf0SP/Ec7iaKmVzkE3THqoWVBUtk=

      # Execution data
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true

    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-workflows:/workflows:ro
    networks:
      - n8n_network

  # Optional: PostgreSQL database for production
  # postgres:
  #   image: postgres:15
  #   container_name: n8n_postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n_password
  #     - POSTGRES_DB=n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - n8n_network

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: n8n_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - certbot_data:/var/www/certbot:ro
      - certbot_conf:/etc/letsencrypt:ro
    networks:
      - n8n_network
    depends_on:
      - n8n

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: n8n_certbot
    volumes:
      - certbot_data:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@waipro.it --agree-tos --no-eff-email -d n8n.waipro.it

volumes:
  n8n_data:
    driver: local
  postgres_data:
    driver: local
  certbot_data:
    driver: local
  certbot_conf:
    driver: local

networks:
  n8n_network:
    driver: bridge
